import random
import typing
# next(), range(), len(), print(), import typing,
# typing.Generator, import random, random.*


PLAYERS: tuple = (
    "jopaz-su",
    "alegalve",
    "aruisnav",
    "jorpere2"
)

ACTIONS: tuple = (
    "code",
    "rest",
    "lift",
    "push-swap"
)


def gen_event():
    while True:
        name: str = random.choice(PLAYERS)
        action: str = random.choice(ACTIONS)
        yield (name, action)


def consume_event(events):
    while events:
        index = random.randrange(len(events))
        yield events.pop(index)


if __name__ == "__main__":
    print("=== Game Data Stream Processor ===")

    g: typing.Generator[tuple[str, str], None, None] = gen_event()
    name: str
    action: str
    name, action = next(g)

    print("\n1000 loops")
    i: int = 1
    while i < 1001:
        name, action = next(g)
        print(f"Event {i}: player {name} did action {action}")
        i += 1
    list_events: list = []
    i = 0
    print("=== Creating a list of 10 events")
    while i < 10:
        list_events.append(next(g))
        i += 1
    print(f"{list_events}")
    print("=== Consuming the list of 10 events")
    for event in consume_event(list_events):
        name, action = event
        left: int = len(list_events)
        print(f"Event: player {name} did action {action}")
        print(f"{left} players/actions left")
        left -= 1
    print("=== End of program")


# This exercise requires the use of generators with the yield
# keyword to create data streams on the fly. You must implement
# generator functions that produce values on-demand
# rather than storing everything in memory.

# Create an endless generator function gen_event() that picks
# a random name from a list of players, and a random action
# from a list of actions.
# Each time next() is called on this
# generator, it returns a new event as a tuple (name, action).

# From the main part of your script, loop a thousand times
# and display all 1000 events you
# get from your gen_event() .

# Then create a list of ten tuples generated by gen_event() again.
# Finally, create a new generator function consume_event that takes
# the previously created
# list, randomly pick one of its elements, remove it from the list,
# and yields it, until the list
# is empty. This generator must be used directly in the for .. in .. construct.
